version: "3"

volumes: 
  data: {}

services: 
  db:
    image: postgres:12
    volumes:
      - data:/var/lib/postgresql/data 
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sickst
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin