class CountyService {

    getCountyList() {
        return [
             'Alba' , 
             'Arad' , 
             'Arges', 
             'Bacau',
             'Bihor',
             'Bistrita-Nasaud',
             'Botosani',
             'Brasov',
             'Braila',
             'Bucuresti',
             'Buzau',
             'Caras-Severin',
             'Calarasi',
             'Cluj',
             'Constanta',
             'Covasna',
             'Dambovita',
             'Dolj',
             'Galati',
             'Giurgiu',
             'Gorj',
             'Harghita',
             'Hunedoara',
             'Ialomita',
             'Iasi',
             'Ilfov',
             'Maramures',
             'Mehedinti',
             'Mures',
             'Neamt',
             'Olt',
             'Prahova',
             'Satu Mare',
             'Salaj',
             'Sibiu',
             'Suceava',
             'Teleorman',
             'Timis',
             'Tulcea',
             'Vaslui',
             'Valcea',
             'Vrancea',
        ]
    }
}

export default new CountyService();