GET http://localhost:8000/category


###
GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS2F5bGUiLCJpYXQiOjE2NTA2NTg0OTd9.9aI1q5eU-OsKPOA16lFxinG6Elczjn5VxcoLI8Q5fZU

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "username": "Kayle"
}

###
GET http://localhost:8000/category

###
POST http://localhost:8000/category
Content-Type: application/json

{
    "name": "Male"
}

###
DELETE http://localhost:8000/category/9

###
POST http://localhost:8000/register

Content-Type: application/json

{
    "email": "e@email.com",
    "password": "password"
}
